name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: 'Test on node ${{ matrix.node_version }} and ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12, 14, 16, 18, 20, 22]
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm test
